Prueba.AppWebMVC/Controllers/BonoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba.AppWebMVC.Models;

namespace Prueba.AppWebMVC.Controllers
{
    public class BonoController : Controller
    {
        private readonly PlanillaScriptContext _context;

        //prueba
        public BonoController(PlanillaScriptContext context)
        {
            _context = context;
        }

        // GET: Bono
        public async Task<IActionResult> Index(Bono bono, int topRegistro = 10)
        {
            var query = _context.Bonos.AsQueryable();

            if (!string.IsNullOrWhiteSpace(bono.NombreBono))
                query = query.Where(s => s.NombreBono.Contains(bono.NombreBono));

            if (bono.Planilla > 0)
                query = query.Where(s => s.Planilla == bono.Planilla);

            if (bono.Estado > 0)
                query = query.Where(s => s.Estado == bono.Estado);

            if (bono.Operacion > 0)
                query = query.Where(s => s.Operacion == bono.Operacion);

            if (topRegistro > 0)
                query = query.Take(topRegistro);

        
            return View(await query.ToListAsync());
        }

        // GET: Bono/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var bono = await _context.Bonos.FirstOrDefaultAsync(m => m.Id == id);
            if (bono == null) return NotFound();

            return View(bono);
        }

        // GET: Bono/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Bono/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NombreBono,Valor,Estado,FechaValidacion,FechaExpiracion,Operacion,Planilla")] Bono bono)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bono);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(bono);
        }

        // GET: Bono/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var bono = await _context.Bonos.FindAsync(id);
            if (bono == null) return NotFound();


            return View(bono);
        }

        // POST: Bono/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NombreBono,Valor,Estado,FechaValidacion,FechaExpiracion,Operacion,Planilla")] Bono bono)
        {
            if (id != bono.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bono);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BonoExists(bono.Id)) return NotFound();
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }

          
            return View(bono);
        }

        // GET: Bono/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var bono = await _context.Bonos.FirstOrDefaultAsync(m => m.Id == id);
            if (bono == null) return NotFound();

            return View(bono);
        }

        // POST: Bono/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bono = await _context.Bonos.FindAsync(id);
            if (bono != null) _context.Bonos.Remove(bono);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BonoExists(int id)
        {
            return _context.Bonos.Any(e => e.Id == id);
        }

        //private void Listado()
        //{
        //    ViewBag.Operaciones = new List<SelectListItem>
        //    {   
        //        new SelectListItem { Value = "1", Text = "Operacion Fija" },
        //        new SelectListItem { Value = "2", Text = "Operacion No Fija" }
        //    };

        //    ViewBag.Estados = new List<SelectListItem>
        //    {
        //        new SelectListItem { Value = "1", Text = "Activo" },
        //        new SelectListItem { Value = "2", Text = "Inactivo" }
        //    };

        //    ViewBag.Planillas = new List<SelectListItem>
        //    {
        //        new SelectListItem { Value = "1", Text = "Mensual" },
        //        new SelectListItem { Value = "2", Text = "Quincenal" }
        //    };
        //}
    }
}

Prueba.AppWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prueba.AppWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Prueba.AppWebMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha384-M3kaT90z4Nbb0xHE7yZ4xwPK1g1zR9f8Vm6hbs8LfIH5FAN1zjUdiMTxJ3yw7tL7" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Prueba.AppWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bono" asp-action="Index">CrudBonos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Descuento" asp-action="Index">CrudDescuentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PuestoTrabajo" asp-action="Index">CrudPuestoTrabajo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="Index">Empleado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JefeInmediato" asp-action="Index">Jefes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AsignacionBonoes" asp-action="Index">BonosAsi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoPlanillas" asp-action="Index">CrudTipolanilla</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planilla" asp-action="Index">CrudPlanilla</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Prueba.AppWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>